# Generated by Django 3.2.7 on 2021-11-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('happy', 'happy'), ('sad', 'sad'), ('fear', 'fear'), ('angry', 'angry'), ('disgust', 'disgust'), ('surprise', 'surprise'), ('neutral', 'neutral')], max_length=50)),
                ('song', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
