# Generated by Django 3.2.7 on 2021-12-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211121_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('happy', 'happy'), ('sad', 'sad'), ('fear', 'fear'), ('angry', 'angry'), ('disgust', 'disgust'), ('surprise', 'surprise'), ('neutral', 'neutral')], max_length=50)),
            ],
        ),
    ]
