# Generated by Django 4.2.7 on 2023-11-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('fantasy', 'Fantasy'), ('science fiction', 'Science Fiction'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('historical fiction', 'Historical Fiction'), ('self-help', 'Self-Help'), ('biography', 'Biography'), ('poetry', 'Poetry')], max_length=50)),
                ('author', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=1000)),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('fear', 'Fear'), ('angry', 'Angry'), ('disgust', 'Disgust'), ('surprise', 'Surprise'), ('neutral', 'Neutral')], max_length=50)),
            ],
        ),
    ]
