# Generated by Django 4.2.7 on 2023-11-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conditions',
        ),
    ]
