# Generated by Django 4.2.7 on 2023-12-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='book_thumbnails/'),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='song',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='song_thumbnails/'),
        ),
    ]
