# Generated by Django 4.2.7 on 2023-12-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_book_description_book_thumbnail_song_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.FileField(upload_to='book_files/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='link',
            field=models.FileField(upload_to='song_files/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
